modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="developer_tool"
version="0.0.3"
displayName="Developer Tool"
credits="null"
displayURL="https://mcreator.net"
authors="HLFT,TangTian"
description='''
RPG Mod
'''

[[dependencies.developer_tool]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




